# Generated by Django 3.2.18 on 2023-03-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Appetizer', 'Appetizer'), ('Entrée', 'Entrée'), ('Dessert', 'Dessert'), ('Snacks', 'Snacks')], default='', max_length=50),
        ),
    ]
